name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      
    - name: Checkout  
      uses: actions/checkout@v1
      with:
        submodules: true
    
    - name: Checkout travis-ci-arduino
      uses: actions/checkout@v2
      with:
         repository: hathach/travis-ci-arduino
         ref: build-platform
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh
    
    - name: test platforms
      run: |
        python3 ci/build_platform.py cpb
